# Generated by Django 2.1.2 on 2018-10-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
